### ISSUE TITLE
Laravel Dusk support

### ISSUE THREAD

**Issue by lsfiege** [GIANTCRAB/gitlabby-dockerish-laravel#13]
Hello! can you add support for run laravel dusk tests? :)

Greetings!

**Comment by GIANTCRAB** [comment]
Sure, I'll get #11 resolved ASAP and thereafter, I'll add this in.

**Comment by GIANTCRAB** [comment]
Laravel Dusk can now be run using woohuiren/php-laravel-env:latest docker image. Let me know if it works for you. Thanks!

**Comment by lsfiege** [comment]
it works
