### ISSUE TITLE
Request: Xdebug for code coverage

### ISSUE THREAD

**Issue by georgo** [GIANTCRAB/gitlabby-dockerish-laravel#6]
Hi,

is there any chance, that Xdebug will be installed and enabled by default in image to allow ```test_job``` to generate code coverage?

Thanks for considering,
Tomas

**Comment by GIANTCRAB** [comment]
Hi, thanks for opening this issue. 

I've added xdebug support in the Docker image and also added code coverage generation here: b841c4ee579d8934199b5ee7c62533f09afe6684
