### ISSUE TITLE
.gitlab-build.sh: line 16: apt-get: not found

### ISSUE THREAD

**Issue by gandra** [GIANTCRAB/gitlabby-dockerish-laravel#8]
Hi @GIANTCRAB !
I have udated deploy script to use image `oohuiren/php-laravel-env:latest`.
Now I have following error:
```
.gitlab-build.sh: line 16: apt-get: not found
ERROR: Job failed: exit code 1
```

I am wondering what OS is inside this image? I have to make some tweaks and install `mysql-client` do some dirty job with multiple DB in my specific env but following command fails:
`apt-get install -y mysql-client`

Best,
Dragan

**Comment by GIANTCRAB** [comment]
Hello! The new image is using Alpine Linux and is smaller in size. You'll need to take a look at the changes made to this repo as well. I would recommend you to use woohuiren/php-laravel-env:5.4 instead in the future as well.

**Comment by gandra** [comment]
Ok.
I have tried latest because somehow I have the problem because database not remains in the test phase.

**Comment by GIANTCRAB** [comment]
Hello, could you kindly elaborate on the issue please? So, there's something wrong with the database... or?

Thanks.
