### ISSUE TITLE
ssh-add <(echo "$SSH_PRIVATE_KEY")

### ISSUE THREAD

**Issue by michaelycus** [GIANTCRAB/gitlabby-dockerish-laravel#9]
When gitlab runner tries to run _.gitlab-key-inject.sh_ the following error appears:

> .gitlab-key-inject.sh: line 9: syntax error: unexpected "("

It seems the following line is causing the error:

`ssh-add <(echo "$SSH_PRIVATE_KEY")`

I don't know how to fix it. It must have to be another way to add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store.

**Comment by Zen0x7** [comment]
I've the same issue with you. My solution was move these scripts to before_scripts section of `gitlab_ci.yml`

```
image: woohuiren/php-laravel-env:latest

services:
  - mysql:latest

before_script:
  # install ssh-agent
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  # run ssh-agent
  - eval $(ssh-agent -s)
  # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  # disable host key checking (NOTE: makes you susceptible to man-in-the-middle attacks)
  # WARNING: use only in docker container, if you use it with shell you will overwrite your user's ssh config
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
```

**Comment by GIANTCRAB** [comment]
Thank you for reporting this issue.

> I've the same issue with you. My solution was move these scripts to before_scripts section of gitlab_ci.yml

Do you mind if I integrate your solution into the repo with credit? Or
you prefer to do a PR?

Thank you.

On a side note, I should start writing some tests to verify this thing
works as changes come in.

Best Regards,
Woo Huiren

"I don't know about you people, but I don't want to live in a world
where someone else makes the world a better place better than we do. "
- Gavin Belson

https://twitter.com/woohuiren

**Comment by GIANTCRAB** [comment]
Thank you @demency for the PR. I've merged it. Also, IIRC, it is because of 'sh' being really old -- it doesn't support `ssh-add <(echo ...)`.

I'll write some tests later and integrate it for all versions/branches. 

If there are any other issues, please feel free to voice them out in this issue or create another issue, thanks again!
